from __future__ import annotations

import logging
from collections import defaultdict
from pathlib import Path

import httpx
from fpdf import FPDF

from benchpress.config import BenchpressConfig, ModelConfig, ProviderConfig
from benchpress.models import BenchmarkRun, ModelSummary

logger = logging.getLogger(__name__)

# Color palette
COLOR_HEADER = (44, 62, 80)
COLOR_ACCENT = (52, 152, 219)
COLOR_GREEN = (39, 174, 96)
COLOR_RED = (231, 76, 60)
COLOR_ORANGE = (243, 156, 18)
COLOR_LIGHT_GRAY = (235, 235, 240)
COLOR_WHITE = (255, 255, 255)
COLOR_MUTED = (120, 120, 130)
COLOR_DARK_TEXT = (40, 40, 40)
COLOR_BODY_TEXT = (60, 60, 60)

PROVIDER_COLORS = [
    (52, 152, 219),   # blue
    (39, 174, 96),    # green
    (155, 89, 182),   # purple
    (243, 156, 18),   # orange
    (231, 76, 60),    # red
    (26, 188, 156),   # teal
]


class BenchpressReport(FPDF):
    def __init__(self) -> None:
        super().__init__(orientation="L", format="A4")
        self.set_auto_page_break(auto=True, margin=20)

    def header(self) -> None:
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(*COLOR_HEADER)
            self.cell(0, 6, "Benchpress Report", align="L")
            self.cell(0, 6, f"Page {self.page_no()}", align="R")
            self.ln(10)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*COLOR_MUTED)
        self.cell(0, 10, "Generated by Benchpress", align="C")


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

async def generate_report(
    run: BenchmarkRun,
    config: BenchpressConfig,
    output_path: str,
) -> str:
    pdf = BenchpressReport()
    summaries = run.summaries

    # Build comparison groups from base_model tags
    comparisons = _build_comparisons(config, summaries)

    # Generate LLM insights (best-effort)
    insights = await _generate_insights(run, config, comparisons)

    # Render pages
    _title_page(pdf, run, insights.get("executive_summary"))
    _head_to_head_pages(pdf, comparisons, insights)
    _unmatched_page(pdf, comparisons, summaries)
    _appendix_tables(pdf, summaries, run)

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    pdf.output(output_path)
    return output_path


# ---------------------------------------------------------------------------
# Comparison grouping
# ---------------------------------------------------------------------------

class ComparisonGroup:
    def __init__(self, base_model: str, display_label: str):
        self.base_model = base_model
        self.display_label = display_label
        self.entries: list[tuple[ProviderConfig, ModelConfig, ModelSummary]] = []


def _build_comparisons(
    config: BenchpressConfig,
    summaries: list[ModelSummary],
) -> list[ComparisonGroup]:
    # Map (provider, model_id) -> ModelSummary
    summary_lookup: dict[tuple[str, str], ModelSummary] = {
        (s.provider, s.model): s for s in summaries
    }

    # Map (provider, model_id) -> (ProviderConfig, ModelConfig)
    config_lookup: dict[tuple[str, str], tuple[ProviderConfig, ModelConfig]] = {}
    for p in config.providers:
        for m in p.models:
            config_lookup[(p.name, m.id)] = (p, m)

    # Group by base_model
    groups: dict[str, ComparisonGroup] = {}
    for p in config.providers:
        for m in p.models:
            if not m.base_model:
                continue
            key = (p.name, m.id)
            summary = summary_lookup.get(key)
            if not summary:
                continue
            if m.base_model not in groups:
                groups[m.base_model] = ComparisonGroup(
                    base_model=m.base_model,
                    display_label=m.base_model.replace("-", " ").title(),
                )
            groups[m.base_model].entries.append((p, m, summary))

    # Only return groups with 2+ entries (actual comparisons)
    return [g for g in groups.values() if len(g.entries) >= 2]


def _get_unmatched(
    comparisons: list[ComparisonGroup],
    summaries: list[ModelSummary],
) -> list[ModelSummary]:
    matched = set()
    for g in comparisons:
        for _, _, s in g.entries:
            matched.add((s.provider, s.model))
    return [s for s in summaries if (s.provider, s.model) not in matched]


# ---------------------------------------------------------------------------
# LLM Insight Generation
# ---------------------------------------------------------------------------

async def _generate_insights(
    run: BenchmarkRun,
    config: BenchpressConfig,
    comparisons: list[ComparisonGroup],
) -> dict[str, str]:
    """Generate LLM insights. Returns dict with 'executive_summary' and per-base_model keys."""
    insights: dict[str, str] = {}

    llm_config = _resolve_llm_config(config)
    if not llm_config:
        return insights

    base_url, model, bearer_token = llm_config

    try:
        insights["executive_summary"] = await _call_llm(
            base_url, model, bearer_token,
            _build_executive_prompt(run, config, comparisons),
        )
    except Exception as e:
        logger.warning(f"Failed to generate executive summary insight: {e}")

    for group in comparisons:
        try:
            insights[group.base_model] = await _call_llm(
                base_url, model, bearer_token,
                _build_comparison_prompt(group, config),
            )
        except Exception as e:
            logger.warning(f"Failed to generate insight for {group.base_model}: {e}")

    return insights


def _resolve_llm_config(
    config: BenchpressConfig,
) -> tuple[str, str, str | None] | None:
    """Returns (base_url, model, bearer_token) or None if not configured."""
    report = config.report

    if report.llm:
        return (
            report.llm.base_url,
            report.llm.model,
            report.llm.resolve_api_key(),
        )

    if report.llm_provider and report.llm_model:
        for p in config.providers:
            if p.name == report.llm_provider:
                return (
                    p.base_url,
                    report.llm_model,
                    p.resolve_api_key(),
                )
        logger.warning(
            f"Report llm_provider '{report.llm_provider}' not found in providers"
        )

    return None


async def _call_llm(
    base_url: str,
    model: str,
    bearer_token: str | None,
    prompt: str,
) -> str:
    headers: dict[str, str] = {"Content-Type": "application/json"}
    if bearer_token:
        headers["Authorization"] = f"Bearer {bearer_token}"

    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 1024,
        "temperature": 0.3,
    }

    async with httpx.AsyncClient(
        base_url=base_url,
        headers=headers,
        timeout=httpx.Timeout(60.0, connect=15.0),
    ) as client:
        resp = await client.post("/chat/completions", json=payload)
        resp.raise_for_status()
        data = resp.json()
        return data["choices"][0]["message"]["content"]


def _build_executive_prompt(
    run: BenchmarkRun,
    config: BenchpressConfig,
    comparisons: list[ComparisonGroup],
) -> str:
    provider_contexts = []
    for p in config.providers:
        ctx = f"- {p.name}"
        if p.insights_context:
            ctx += f": {p.insights_context.strip()}"
        provider_contexts.append(ctx)

    summary_lines = []
    for s in run.summaries:
        summary_lines.append(
            f"  {s.display_name} ({s.provider}): "
            f"success={s.success_rate:.0f}%, "
            f"avg_ms={s.avg_total_ms:.0f}, "
            f"p95_ms={s.p95_total_ms:.0f}, "
            f"tool_acc={s.avg_tool_accuracy:.1%}, "
            f"coherence={s.avg_coherence:.1%}, "
            f"cost=${s.total_cost_usd:.4f}"
        )

    comparison_lines = []
    for g in comparisons:
        entries = ", ".join(
            f"{m.display_name} ({p.name})" for p, m, _ in g.entries
        )
        comparison_lines.append(f"  {g.display_label}: {entries}")

    return f"""You are writing the executive summary for a benchmark report comparing LLM providers.
Write 2-3 concise paragraphs summarizing the key findings. Be balanced and constructive.

Provider context:
{chr(10).join(provider_contexts)}

Benchmark results:
{chr(10).join(summary_lines)}

Head-to-head comparisons:
{chr(10).join(comparison_lines)}

Configuration: {run.config_summary}

Guidelines:
- Lead with the most important finding
- Compare providers constructively, acknowledging each provider's value proposition
- Mention specific numbers (latency, accuracy, cost) to support claims
- Keep it professional and suitable for stakeholder presentations
- If all requests failed for a provider, note this factually and suggest possible causes
- Do not use markdown formatting, bullet points, or headers — write flowing prose paragraphs"""


def _build_comparison_prompt(
    group: ComparisonGroup,
    config: BenchpressConfig,
) -> str:
    entries_text = []
    for p, m, s in group.entries:
        ctx = ""
        if p.insights_context:
            ctx = f"\n    Provider context: {p.insights_context.strip()}"
        entries_text.append(
            f"  {m.display_name} ({p.name}):{ctx}\n"
            f"    Success: {s.success_rate:.0f}% ({s.success_count}/{s.total_requests})\n"
            f"    Latency: avg={s.avg_total_ms:.0f}ms, p50={s.p50_total_ms:.0f}ms, p95={s.p95_total_ms:.0f}ms\n"
            f"    TTFB: avg={s.avg_ttfb_ms:.0f}ms, p95={s.p95_ttfb_ms:.0f}ms\n"
            f"    Quality: tool_acc={s.avg_tool_accuracy:.1%}, coherence={s.avg_coherence:.1%}, relevance={s.avg_relevance:.1%}\n"
            f"    Cost: total=${s.total_cost_usd:.4f}, per_request=${s.avg_cost_per_request:.5f}\n"
            f"    Tokens: total_input={s.total_input_tokens:,}, total_output={s.total_output_tokens:,}, "
            f"avg_input={s.avg_input_tokens:.0f}, avg_output={s.avg_output_tokens:.0f}"
        )

    return f"""You are writing a comparison insight for the base model "{group.display_label}" deployed across different providers.
Write 1-2 concise paragraphs comparing these deployments. Be constructive and balanced.

Deployments:
{chr(10).join(entries_text)}

Guidelines:
- Highlight meaningful differences in latency, quality, and cost
- Use delta language: "X is Nms faster" or "Y costs Z% less"
- Acknowledge each provider's value-add per the provider context
- If one provider had failures, note it factually without harsh judgment
- Keep it professional and suitable for stakeholder presentations
- Do not use markdown formatting, bullet points, or headers — write flowing prose paragraphs"""


# ---------------------------------------------------------------------------
# PDF Page Rendering
# ---------------------------------------------------------------------------

def _title_page(
    pdf: BenchpressReport,
    run: BenchmarkRun,
    executive_insight: str | None,
) -> None:
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 32)
    pdf.set_text_color(*COLOR_HEADER)
    pdf.ln(15)
    pdf.cell(0, 16, "Benchpress Report", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(*COLOR_MUTED)
    pdf.cell(0, 8, run.timestamp, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Config summary
    cfg = run.config_summary
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*COLOR_HEADER)
    pdf.cell(0, 7, "Test Configuration", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*COLOR_BODY_TEXT)

    config_text = (
        f"  Requests/model: {cfg.get('num_requests', 'N/A')}  |  "
        f"Concurrency: {cfg.get('concurrency', 'N/A')}  |  "
        f"Interval: {cfg.get('interval_ms', 'N/A')}ms  |  "
        f"Temperature: {cfg.get('temperature', 'N/A')}  |  "
        f"Max tokens: {cfg.get('max_tokens', 'N/A')}  |  "
        f"Seed: {cfg.get('seed', 'N/A')}"
    )
    pdf.cell(0, 5, config_text, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Models tested
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*COLOR_HEADER)
    pdf.cell(0, 7, "Models Tested", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*COLOR_BODY_TEXT)
    for s in run.summaries:
        pdf.cell(0, 5, f"  {s.display_name} via {s.provider}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Winner badges (only from successful runs)
    successful = [s for s in run.summaries if s.success_count > 0]
    if successful:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*COLOR_HEADER)
        pdf.cell(0, 7, "Highlights", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)

        fastest = min(successful, key=lambda s: s.avg_total_ms)
        pdf.set_text_color(*COLOR_GREEN)
        pdf.cell(
            0, 5,
            f"  Fastest: {fastest.display_name} ({fastest.provider}) at {fastest.avg_total_ms:.0f}ms avg",
            new_x="LMARGIN", new_y="NEXT",
        )

        most_accurate = max(successful, key=lambda s: s.avg_tool_accuracy)
        pdf.set_text_color(*COLOR_ACCENT)
        pdf.cell(
            0, 5,
            f"  Most Accurate: {most_accurate.display_name} ({most_accurate.provider}) "
            f"at {most_accurate.avg_tool_accuracy:.1%}",
            new_x="LMARGIN", new_y="NEXT",
        )

        with_cost = [s for s in successful if s.avg_cost_per_request > 0]
        if with_cost:
            cheapest = min(with_cost, key=lambda s: s.avg_cost_per_request)
            pdf.set_text_color(*COLOR_ORANGE)
            pdf.cell(
                0, 5,
                f"  Best Value: {cheapest.display_name} ({cheapest.provider}) "
                f"at ${cheapest.avg_cost_per_request:.4f}/request",
                new_x="LMARGIN", new_y="NEXT",
            )
        pdf.ln(3)

    # Executive summary insight
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*COLOR_HEADER)
    pdf.cell(0, 7, "Executive Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*COLOR_BODY_TEXT)

    if executive_insight:
        pdf.multi_cell(0, 5, f"  {executive_insight}", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.set_text_color(*COLOR_MUTED)
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(
            0, 5,
            "  Configure report.llm_provider to enable generated insights.",
            new_x="LMARGIN", new_y="NEXT",
        )


def _head_to_head_pages(
    pdf: BenchpressReport,
    comparisons: list[ComparisonGroup],
    insights: dict[str, str],
) -> None:
    if not comparisons:
        return

    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*COLOR_HEADER)
    pdf.cell(0, 12, "Head-to-Head Comparisons", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    for i, group in enumerate(comparisons):
        # Check if we need a new page (need ~80mm for a comparison)
        if pdf.get_y() > 130:
            pdf.add_page()

        _render_comparison(pdf, group, insights.get(group.base_model))

        if i < len(comparisons) - 1:
            pdf.ln(5)
            # Separator line
            y = pdf.get_y()
            pdf.set_draw_color(*COLOR_LIGHT_GRAY)
            pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
            pdf.ln(5)


def _render_comparison(
    pdf: BenchpressReport,
    group: ComparisonGroup,
    insight: str | None,
) -> None:
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*COLOR_HEADER)
    pdf.cell(0, 9, group.display_label, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    entries = group.entries
    n = len(entries)

    # Metrics comparison table
    metrics = [
        ("Success Rate", lambda s: f"{s.success_rate:.0f}%", lambda s: s.success_rate, True),
        ("Avg Latency", lambda s: f"{s.avg_total_ms:.0f}ms", lambda s: s.avg_total_ms, False),
        ("P95 Latency", lambda s: f"{s.p95_total_ms:.0f}ms", lambda s: s.p95_total_ms, False),
        ("Avg TTFB", lambda s: f"{s.avg_ttfb_ms:.0f}ms", lambda s: s.avg_ttfb_ms, False),
        ("Avg In Tokens", lambda s: f"{s.avg_input_tokens:.0f}", lambda s: s.avg_input_tokens, False),
        ("Avg Out Tokens", lambda s: f"{s.avg_output_tokens:.0f}", lambda s: s.avg_output_tokens, False),
        ("Total Tokens", lambda s: f"{s.total_input_tokens + s.total_output_tokens:,}", lambda s: s.total_input_tokens + s.total_output_tokens, False),
        ("Tool Accuracy", lambda s: f"{s.avg_tool_accuracy:.1%}", lambda s: s.avg_tool_accuracy, True),
        ("Coherence", lambda s: f"{s.avg_coherence:.1%}", lambda s: s.avg_coherence, True),
        ("Cost/Request", lambda s: f"${s.avg_cost_per_request:.5f}", lambda s: s.avg_cost_per_request, False),
    ]

    label_w = 35
    col_w = min(55, (pdf.w - pdf.l_margin - pdf.r_margin - label_w - 50) / n)
    delta_w = 45

    # Header row: metric | provider1 | provider2 | delta
    pdf.set_font("Helvetica", "B", 7)
    pdf.set_fill_color(*COLOR_HEADER)
    pdf.set_text_color(*COLOR_WHITE)
    pdf.cell(label_w, 7, "Metric", border=1, fill=True, align="C")
    for p, m, s in entries:
        label = f"{m.display_name[:18]} ({p.name[:10]})"
        pdf.cell(col_w, 7, label, border=1, fill=True, align="C")
    if n == 2:
        pdf.cell(delta_w, 7, "Delta", border=1, fill=True, align="C")
    pdf.ln()

    # Data rows
    pdf.set_font("Helvetica", "", 7)
    for row_i, (metric_name, fmt_fn, val_fn, higher_is_better) in enumerate(metrics):
        bg = COLOR_WHITE if row_i % 2 == 0 else COLOR_LIGHT_GRAY
        pdf.set_fill_color(*bg)
        pdf.set_text_color(*COLOR_DARK_TEXT)

        pdf.set_font("Helvetica", "B", 7)
        pdf.cell(label_w, 6, metric_name, border=1, fill=True, align="L")

        pdf.set_font("Helvetica", "", 7)
        values = []
        for _, _, s in entries:
            val_str = fmt_fn(s)
            raw_val = val_fn(s)
            values.append(raw_val)
            pdf.cell(col_w, 6, val_str, border=1, fill=True, align="C")

        # Delta column for 2-entry comparisons
        if n == 2 and values[0] != 0 and values[1] != 0:
            diff = values[1] - values[0]
            if "ms" in metric_name.lower() or "latency" in metric_name.lower() or "ttfb" in metric_name.lower():
                delta_str = f"{diff:+.0f}ms"
            elif "%" in fmt_fn(entries[0][2]):
                delta_str = f"{diff:+.1%}"
            elif "$" in fmt_fn(entries[0][2]):
                delta_str = f"${diff:+.5f}"
            else:
                delta_str = f"{diff:+.2f}"

            # Color: green if favorable, red if not
            is_favorable = (diff > 0) if higher_is_better else (diff < 0)
            if diff == 0:
                pdf.set_text_color(*COLOR_MUTED)
                delta_str = "same"
            elif is_favorable:
                pdf.set_text_color(*COLOR_GREEN)
            else:
                pdf.set_text_color(*COLOR_RED)

            pdf.cell(delta_w, 6, delta_str, border=1, fill=True, align="C")
            pdf.set_text_color(*COLOR_DARK_TEXT)
        elif n == 2:
            pdf.cell(delta_w, 6, "-", border=1, fill=True, align="C")

        pdf.ln()

    # Insight paragraph
    pdf.ln(3)
    if insight:
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*COLOR_BODY_TEXT)
        pdf.multi_cell(0, 4.5, insight, new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(*COLOR_MUTED)
        pdf.cell(
            0, 4.5,
            "Configure report.llm_provider to enable generated insights.",
            new_x="LMARGIN", new_y="NEXT",
        )


def _unmatched_page(
    pdf: BenchpressReport,
    comparisons: list[ComparisonGroup],
    summaries: list[ModelSummary],
) -> None:
    unmatched = _get_unmatched(comparisons, summaries)
    if not unmatched:
        return

    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*COLOR_HEADER)
    pdf.cell(0, 12, "Additional Models", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*COLOR_BODY_TEXT)
    pdf.cell(
        0, 6,
        "Models without cross-provider comparisons (no base_model match).",
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.ln(3)

    _render_summary_table(pdf, unmatched)


def _appendix_tables(
    pdf: BenchpressReport,
    summaries: list[ModelSummary],
    run: BenchmarkRun,
) -> None:
    if not summaries:
        return

    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*COLOR_HEADER)
    pdf.cell(0, 12, "Data Appendix", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Full comparison table
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*COLOR_HEADER)
    pdf.cell(0, 8, "All Models", new_x="LMARGIN", new_y="NEXT")
    _render_summary_table(pdf, summaries)

    # Per-category breakdown
    pdf.ln(5)
    if pdf.get_y() > 140:
        pdf.add_page()

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*COLOR_HEADER)
    pdf.cell(0, 8, "Per-Category Breakdown", new_x="LMARGIN", new_y="NEXT")

    cat_headers = ["Model", "Category", "Count", "Success", "Tool Acc", "Coherence", "Avg ms"]
    cat_widths = [55, 40, 20, 20, 25, 25, 25]

    pdf.set_font("Helvetica", "B", 7)
    pdf.set_fill_color(*COLOR_HEADER)
    pdf.set_text_color(*COLOR_WHITE)
    for h, w in zip(cat_headers, cat_widths):
        pdf.cell(w, 7, h, border=1, fill=True, align="C")
    pdf.ln()

    pdf.set_font("Helvetica", "", 7)
    row_i = 0
    for s in summaries:
        for bd in s.category_breakdowns:
            if pdf.get_y() > 180:
                pdf.add_page()
                pdf.set_font("Helvetica", "B", 7)
                pdf.set_fill_color(*COLOR_HEADER)
                pdf.set_text_color(*COLOR_WHITE)
                for h, w in zip(cat_headers, cat_widths):
                    pdf.cell(w, 7, h, border=1, fill=True, align="C")
                pdf.ln()
                pdf.set_font("Helvetica", "", 7)

            bg = COLOR_WHITE if row_i % 2 == 0 else COLOR_LIGHT_GRAY
            pdf.set_fill_color(*bg)
            pdf.set_text_color(*COLOR_DARK_TEXT)
            row = [
                s.display_name[:22],
                bd.category,
                str(bd.count),
                str(bd.success_count),
                f"{bd.avg_tool_accuracy:.0%}",
                f"{bd.avg_coherence:.0%}",
                f"{bd.avg_total_ms:.0f}",
            ]
            for val, w in zip(row, cat_widths):
                pdf.cell(w, 6, val, border=1, fill=True, align="C")
            pdf.ln()
            row_i += 1

    # Error summary
    errors_by_provider: dict[str, list] = defaultdict(list)
    for r in run.results:
        if r.status in ("error", "timeout"):
            errors_by_provider[r.provider].append(r)

    if errors_by_provider:
        pdf.ln(5)
        if pdf.get_y() > 150:
            pdf.add_page()

        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*COLOR_HEADER)
        pdf.cell(0, 8, "Error Summary", new_x="LMARGIN", new_y="NEXT")

        for provider, errors in errors_by_provider.items():
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*COLOR_RED)
            pdf.cell(
                0, 6,
                f"{provider}: {len(errors)} error(s)",
                new_x="LMARGIN", new_y="NEXT",
            )
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*COLOR_BODY_TEXT)
            # Show up to 3 sample errors
            seen_messages: set[str] = set()
            shown = 0
            for r in errors:
                msg = (r.error_message or "Unknown")[:120]
                if msg not in seen_messages and shown < 3:
                    seen_messages.add(msg)
                    pdf.cell(
                        0, 5,
                        f"  [{r.status}] {msg}",
                        new_x="LMARGIN", new_y="NEXT",
                    )
                    shown += 1
            pdf.ln(2)


def _render_summary_table(
    pdf: BenchpressReport,
    summaries: list[ModelSummary],
) -> None:
    headers = [
        "Model", "Provider", "Success%", "Avg TTFB", "P95 TTFB",
        "Avg Total", "Avg In", "Avg Out", "Tokens", "Tool Acc", "Cost",
    ]
    col_widths = [45, 30, 22, 23, 23, 23, 20, 20, 26, 22, 24]

    pdf.set_font("Helvetica", "B", 7)
    pdf.set_fill_color(*COLOR_HEADER)
    pdf.set_text_color(*COLOR_WHITE)
    for header, w in zip(headers, col_widths):
        pdf.cell(w, 7, header, border=1, fill=True, align="C")
    pdf.ln()

    pdf.set_font("Helvetica", "", 7)
    for i, s in enumerate(summaries):
        if pdf.get_y() > 180:
            pdf.add_page()
            pdf.set_font("Helvetica", "B", 7)
            pdf.set_fill_color(*COLOR_HEADER)
            pdf.set_text_color(*COLOR_WHITE)
            for header, w in zip(headers, col_widths):
                pdf.cell(w, 7, header, border=1, fill=True, align="C")
            pdf.ln()
            pdf.set_font("Helvetica", "", 7)

        bg = COLOR_WHITE if i % 2 == 0 else COLOR_LIGHT_GRAY
        pdf.set_fill_color(*bg)
        pdf.set_text_color(*COLOR_DARK_TEXT)

        row = [
            s.display_name[:18],
            s.provider,
            f"{s.success_rate:.0f}%",
            f"{s.avg_ttfb_ms:.0f}ms",
            f"{s.p95_ttfb_ms:.0f}ms",
            f"{s.avg_total_ms:.0f}ms",
            f"{s.avg_input_tokens:.0f}",
            f"{s.avg_output_tokens:.0f}",
            f"{s.total_input_tokens + s.total_output_tokens:,}",
            f"{s.avg_tool_accuracy:.0%}",
            f"${s.total_cost_usd:.3f}",
        ]
        for val, w in zip(row, col_widths):
            pdf.cell(w, 6, val, border=1, fill=True, align="C")
        pdf.ln()
